<a href="https://colab.research.google.com/github/Enthusiasmile/Numpy-Pandas_Codes/blob/main/Notes5(Numpy_%26_Pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [79]:
import numpy as np #calling numpy #np is alia's name

In [80]:
l2=np.array([1,2,3,2,52,5,5,2,5,8,5,8,5,8]) #converting any list into array #np.array()
print(l2)

[ 1  2  3  2 52  5  5  2  5  8  5  8  5  8]


In [81]:
type(l2) #ndarray= n dimensional array

numpy.ndarray

In [82]:
l2.ndim # .ndim shows no. of dimwnsions ie. 1D

1

In [83]:
l2.shape

(14,)

In [84]:
la=[12,25,15,24] #multidimensional array / multinested array
lb=[22,11,45,66]
lc=[56,25,66,33]

In [85]:
ld=np.array([la,lb,lc]) 
print(ld)

[[12 25 15 24]
 [22 11 45 66]
 [56 25 66 33]]


In [86]:
type(ld) #ndimensional here n=2 ie 2d array

numpy.ndarray

In [87]:
ld.ndim #2 = 2dimensional

2

In [88]:
ld.size # .size shows total no. of elements

12

In [89]:
ld.shape #shows no.of rows and columns in array.

(3, 4)

In [90]:
print(ld.reshape(4,3)) #reshapes as per corresponding no.of rows and columns

[[12 25 15]
 [24 22 11]
 [45 66 56]
 [25 66 33]]


In [91]:
ld.max() #maximum value in dataset

66

In [92]:
ld.max(axis=0) #maximum value in columns 0=column

array([56, 25, 66, 66])

In [93]:
ld.min() #minimum value in dataset

11

In [94]:
np.sum(ld) #sum of total elements in dataset

400

In [95]:
ld.T #transpose of ld

array([[12, 22, 56],
       [25, 11, 25],
       [15, 45, 66],
       [24, 66, 33]])

OR

In [96]:
ld.transpose() #transpose of ld

array([[12, 22, 56],
       [25, 11, 25],
       [15, 45, 66],
       [24, 66, 33]])

In [97]:
ld.ravel() #multidimensional array into 1D array

array([12, 25, 15, 24, 22, 11, 45, 66, 56, 25, 66, 33])

In [98]:
one=np.ones((5,3),dtype=int) #np.ones creates dataset of elements having value 1. 
print(one)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [99]:
one=np.ones((5,3),dtype=float) #1 in float format
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [100]:
one=np.ones((5,3),dtype=str) #1 in string format
print(one)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [101]:
one=np.ones((5,3),dtype=bool) #1 in boolian format
print(one)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [102]:
zero=np.zeros((5,8),dtype=int) #0 in boolian format 
print(zero)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [103]:
zero=np.zeros((5,8),dtype=bool) #np.zeros creates dataset of elements having value 0. 
print(zero)

[[False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]]


In [104]:
e=np.empty((4,3)) #np.empty creates dataset of random elements
print(e)

[[5.93e-323 1.24e-322 7.41e-323]
 [1.19e-322 1.09e-322 5.43e-323]
 [2.22e-322 3.26e-322 2.77e-322]
 [1.24e-322 3.26e-322 1.63e-322]]


In [105]:
e=np.empty((2,4),dtype=int) #integer
print(e)

[[        9793376         9793696         9794016         9794336]
 [        9796256         9799456 140044954483728 140046136430128]]


In [106]:
#generating numbers
g=np.arange(1,10) #create dataset of given range
print(g)

[1 2 3 4 5 6 7 8 9]


In [107]:
g=np.arange(2,21,2) #2=stepsize
print(g)

[ 2  4  6  8 10 12 14 16 18 20]


In [108]:
a=np.arange(1,21).reshape(4,5) #create dataset of given range in required dimensional format
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [109]:
l=np.linspace(1,10) #creates 50 elements(by default) between given range
print(l)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [110]:
l=np.linspace(5,50,10) #10= no. of unique elements in given range
print(l)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [111]:
l=np.linspace(5,50,10,dtype=int) #int
print(l)

[ 5 10 15 20 25 30 35 40 45 50]


In [112]:
#indexing and slicing
i=np.arange(1,21).reshape(4,5)
print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [113]:
i[:,:] #feches rows before(,) and feches columns after(,)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [114]:
i[0:2,3:]

array([[ 4,  5],
       [ 9, 10]])

In [115]:
#creating random number datasett
import random

In [116]:
np.random.rand(1) #single(1D) random value between 0-1

array([0.87012017])

In [117]:
np.random.rand(3,4) #3=no.of rows,4=no.of columns from range 0-1,1=exclusive

array([[0.54967401, 0.10530977, 0.90783677, 0.84859983],
       [0.91784913, 0.96280713, 0.16232636, 0.51947261],
       [0.69694376, 0.06541147, 0.96419012, 0.65259681]])

In [118]:
np.random.randn(5,5) #randn gives +ve as well as -ve values

array([[ 1.27449729,  1.26685119, -0.52396924, -0.92883294,  1.94307865],
       [-0.36717788, -0.6656988 ,  1.4249657 ,  0.30714886, -1.24636852],
       [ 0.45281017,  1.8814926 , -0.63095897,  0.31415124, -0.45098649],
       [ 0.51311688, -0.29201858,  0.40525128, -2.34963295,  0.77454338],
       [-0.55154437, -0.09142923,  0.17067662,  0.85628593, -2.39692607]])

In [119]:
np.random.randint(1,10)

1

In [120]:
np.random.randint(1,10,20) #1-10 is range 20=no.of random elements

array([4, 7, 6, 1, 7, 6, 4, 9, 1, 1, 5, 8, 8, 1, 9, 7, 4, 5, 8, 3])

In [121]:
np.random.randint(1,50,(4,4)) #1,50=range, (4,4)=shape ie. 2D array

array([[30,  2, 30, 23],
       [26, 48, 47, 48],
       [34, 12, 42,  6],
       [31, 45, 44,  2]])

In [122]:
np.random.randint(1,50,(2,4,4)) #3D

array([[[46, 41, 11,  8],
        [16, 27, 37,  7],
        [49, 20, 39, 43],
        [44, 24, 19, 26]],

       [[35, 31, 26, 36],
        [34, 44, 39, 23],
        [34, 19,  2,  3],
        [ 6,  4, 23, 22]]])

In [123]:
#finding trigonometry
np.sin(180) # value in degree

-0.8011526357338304

In [124]:
np.sin(180*np.pi/180) #value in radian

1.2246467991473532e-16

In [125]:
np.cos(180) # value in degree

-0.5984600690578581

In [126]:
np.cos(180*np.pi/180) #value in radian

-1.0

In [127]:
np.cos(180*np.pi/180) # value in degree

-1.0

In [128]:
np.cos(90*np.pi/90) #value in radian

-1.0

In [129]:
np.tan(90) # value in degree

-1.995200412208242

In [130]:
np.tan(180*np.pi/180) #value in radian

-1.2246467991473532e-16

PANDAS
1. Loading and reading the data

2. Statistical analysis of data

3. Creating the structure of dummy dataset

In [131]:
import pandas as pd #pd is the alias name

In [132]:
pd.__version__

'1.3.5'

In [133]:
#SERIES

l=[789,-859,'india',-55,88,-1546]
print(l)

[789, -859, 'india', -55, 88, -1546]


In [134]:
series=pd.Series(l)
print(series)

0      789
1     -859
2    india
3      -55
4       88
5    -1546
dtype: object


In [135]:
type(series)

pandas.core.series.Series

In [136]:
series2=pd.Series((1,2,3,4,5))
print(series2)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [137]:
series3=pd.Series((1,2,3,4,5),index=('a','b','c','d','e')) #modify indexing
print(series3)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [138]:
series4=pd.Series((1,2,3,4,5),index=('a','b','c','d','e'),dtype=float) #changeing data type
print(series4)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64


In [139]:
series5=pd.Series((1,2,3,4,5),index=('a','b','c','d','e'),dtype=float,name='number') #naming to data
print(series5)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: number, dtype: float64


In [140]:
scalar1=pd.Series((0.01)) #for scalar values
print(scalar1)

0    0.01
dtype: float64


In [141]:
scalar2=pd.Series((0.01),index=('a','b','c','d')) #Series of a scalar value
print(scalar2)

a    0.01
b    0.01
c    0.01
d    0.01
dtype: float64


In [142]:
dict1=pd.Series({'a':1,'b':2,'c':3,'d':4}) #dictionary
print(dict1)

a    1
b    2
c    3
d    4
dtype: int64


In [143]:
dict1[0] #indexing

1

In [144]:
dict1[1:5] #slicing

b    2
c    3
d    4
dtype: int64

In [145]:
max(dict1)  #max value in series

4

In [146]:
min(dict1) #min value in series

1

In [147]:
a=pd.Series((1,2,3,4,5)) 
b=pd.Series((5,6,7,8,10))
print(a+b)   #adding 2 series

0     6
1     8
2    10
3    12
4    15
dtype: int64


In [148]:
a=pd.Series((1,2,3,4,5)) 
b=pd.Series((5,6,7,))
print(a+b) #handles missing data

0     6.0
1     8.0
2    10.0
3     NaN
4     NaN
dtype: float64


In [149]:
#Dataframe- size mutable, 2D tabular strucure
emt=pd.DataFrame()
index=[]
columns=[]
print(emt) #empty dataframe

Empty DataFrame
Columns: []
Index: []


In [150]:
l=['a','b','c','d']
d=pd.DataFrame(l)
d

0
0  a
1  b
2  c
3  d

In [151]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
d1=pd.DataFrame(l1)
d1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [152]:
dict1={'id':[1,2,3,4]}
d2=pd.DataFrame(dict1)
d2 #dataframe using dictionary

id
0   1
1   2
2   3
3   4

In [153]:
dict2={'id':[1,2,3,4],'name':['tushar','kiran','pawan','onkar']}
d3=pd.DataFrame(dict2)

In [154]:
d3

id    name
0   1  tushar
1   2   kiran
2   3   pawan
3   4   onkar

In [155]:
dict3=[{'a':10,'b':20,'c':30,'d':40},{'a':100,'b':200,'c':300,'d':400}]
d4=pd.DataFrame(dict3)
d4

a    b    c    d
0   10   20   30   40
1  100  200  300  400

In [156]:
dict5=[{'a':10,'b':20,'c':30,'d':40},{'a':100,'b':200,'c':300}]
d6=pd.DataFrame(dict5)
d6 #handles missing

a    b    c     d
0   10   20   30  40.0
1  100  200  300   NaN

In [157]:
my_data=pd.DataFrame(np.arange(0,20).reshape(4,5),index=['row1','row2','row3','row4'],columns=['col1','col2','col3','col4','col5'])
print(my_data)

      col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19


In [158]:
#saving dummy dataset
my_data.to_csv('dummy_data') #for csv file

In [159]:
my_data.to_excel('demo_topmento.xlsx') #foe excel file

In [160]:
#fetching values from the dataset - iloc[]
my_data.iloc[0:3,1:4]   

col2  col3  col4
row1     1     2     3
row2     6     7     8
row3    11    12    13

In [161]:
#reading cvs files
data=pd.read_csv('/tips[1].csv')

In [162]:
data.head() #shows 1st 5 rows

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [163]:
data.tail() #last 5 rows

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [164]:
data.info #general information of data

<bound method DataFrame.info of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [165]:
data.describe() #statistical information of data

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [166]:
type(data)

pandas.core.frame.DataFrame

In [167]:
data.columns #displays column names

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [168]:
data.index #displays index

RangeIndex(start=0, stop=244, step=1)

In [169]:
data.iloc[0:1] #slicing

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2

In [170]:
data.iloc[0:5,0:2]

total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50
3       23.68  3.31
4       24.59  3.61